### ISSUE TITLE
Mining on g4ad.xlarge with Radeon Pro V520

### ISSUE THREAD

**Issue by BE-CH** [mludvig/aws-ethereum-miner#25]
Thanks for your work in the AWS mining field, @mludvig !

I was looking around at the different instances with GPU's and I found the ``G4ad instances``.
They all seem to have ``AMD Radeon Pro V520 GPUs`` that looks really good for mining.

This youtube video showcasing (a slight modified version of V520) **70 MH/s** mining ETH!
https://www.youtube.com/watch?v=WMaPkCYJ1WA

The price of g4ad.xlarge linux on demand is just **$0,38 pr. hour**! I have done some calculations, and with this info it seems like its the pest price pr. MH/s coming in at 184 MH/s pr. $1 (Linux on demand price).

**Have you tested the G4AD instances? If so, what was your results?**

**Comment by mludvig** [comment]
The video says it's modified and overclocked so the hashrate on g4ad is almost certainly going to be less. Still may be worth it,  I may have to look at it sometime.

The trouble is that AMD Radeons need a different software, both the OS drivers and the mining software since they're not NVIDIA / CUDA compatible.

**Comment by BE-CH** [comment]
I just tested AMD Radeons V520 on the g4ad.xlarge. They mine without a problem.

**They are each running 48-50 MH/s on AWS**. So quite a bit less than the 70 MH/s seen in the video.

On demand for g4ad.xlarge is running 131 MH/s pr 1$. 
Spot pricing for g4ad.xlarge is running 389 MH/s pr. 1$

Tho getting a spot instance of g4ad.xlarge is basically impossible, at least in my experience.

**Comment by hermitico** [comment]
Hi all,

What is the most cost-effective setup these days?

Merry Xmas!

**Comment by mludvig** [comment]
@BE-CH can you test the updated templates to see if it works for you? They now support G4ad instances.

**Comment by jxu** [comment]
Are the new Radeon AMI, ex. ami-0f28b3a6ec09b33d5 for us-east-2, custom made with OpenCL installed?

**Comment by mludvig** [comment]
@jxu what if you run the template as-is in us-east-2? Does it work? If it does then it’s a compatibility issue with your software.

**Comment by jxu** [comment]
The template as-is does not run for me. I have no experience with AWS Stacks - it reports the stack was created successfully, but AFAIK no instances are running. I also noticed I couldn't seem to ever get spot instances so I set it to both on-demand and spot. I'm not sure what the issue is as I haven't ever used AWS Session Manager and no instances showed up there.

What I did for now is just run ethminer on a manually created instance using more or less the startup script from the default template without setting up a stack.

**Comment by jxu** [comment]
I guess it is something not setup with the specific AMI. TeamRedMiner reports something similar:

```
[2022-01-05 22:07:00] Auto-detected AMD OpenCL platform 0
[2022-01-05 22:07:00] Failed to list OpenCL devices for platform 0.
```

**Comment by mludvig** [comment]
@jxu spot are sometimes hard to get but if you get ondemand going in then try to login to it via SSM - select the instance, and click “Connect” in the top-right set of buttons. Then select Session Manager and Connect. You should get a black screen with a “$” prompt. Then you can run `sudo su -` to get a proper root shell. Check what the output is in `/tmp/ethminer.log`.

**Comment by jxu** [comment]
Ok for some reason before instances weren't showing up - maybe because I couldn't get spot instances?
I set instanceType to g4ad.xlarge and spot or on-demand to both. Now the instances seemed to boot and the log is reporting about 50 Mh/s which seems correct. 

So I'm still not sure what was wrong with me testing ethminer on the custom AMI without a stack unless the stack setup does extra opencl installation or something. Also I only see one instance running - if I used default hashrate of 250, shouldn't it spin up 5 instances? I'm not sure how AWS stacks work.

**Comment by mludvig** [comment]
The Radeon AMI should boot up with OpenCL ready to go, not sure what happend with your instance. 

It may take some time to get all the instances, esp if you’re using ‘spot’ or ‘both’. Also note that with ‘both’ it will do 50% spot and 50% ondemand.

**Comment by jxu** [comment]
Ok it looks like 2/4 of my instances are spot and they just took a while. I would go with 100% spot but idk how long I'd be waiting.

The instances are using the same exact ami-0f28b3a6ec09b33d5 radeon AMIs so idk why the manually created instances didn't work.

**Comment by naturalesteban** [comment]
Hey Michael, thanks for this template so far so good with an avg of 800MH/s and 32 gdns. Do you think this arrow-glacier update affects the performance?

**Comment by mgeeforce** [comment]
I am having a similar experience using the RadeonX8664 image: ami-04ad2df5b2bf97fd5 in ca-central-1. clinfo isn't installed and after installing it - "no devices found in platform". The template itself fails as tries to deploy a g4ad.16xlarge, regardless of hash rate specified , which isn't available in my default region.

**Comment by jxu** [comment]
> The template itself fails as tries to deploy a g4ad.16xlarge, regardless of hash rate specified , which isn't available in my default region.

Which instances did you put into the template parameters? Only put instances that are available in your chosen region.

**Comment by mludvig** [comment]
@mgeeforce @jxu I've just fixed the issue with **ca-central-1** - I had to explicitly exclude _g4ad.8xlarge_ and _g4ad.16xlarge_ in that region. They are reported as available by the EC2 API but don't actually work, go figure... Try the deployment again please and let me know.
Commit 23065e3
