### ISSUE TITLE
How to run multiple instances of this on AWS? + Some general questions

### ISSUE THREAD

**Issue by blueboy90780** [mludvig/aws-ethereum-miner#36]
I've launched one instance of this on AWS. But how do launch multiple miners with multiple workers?

Also, how do I detect the hash rate for these things and benchmark them like you did? I want to try benchmarking them on other cryptocurrencies as well.

Will this instance run for 24 hours?

**Comment by mludvig** [comment]
Check the Instances in the EC2 console - how many are running? If you see only 1 instance it could be because…

- it’s a big enough instance to meet your hashrate requirement, or
- your service limits don’t allow more, or
- spot capacity is not available in that region right now

If you want to run more instances increase the required hashrate in the stack parameters and make sure that your service limits are high enough.
